.TH DALLE-SFV-CONSOLE "1" "March 30, 2009"
.SH NAME
dalle\-sfv\-console \- Utility to verify files

.SH SYNOPSIS
.B TODO

.SH DESCRIPTION
\fBdalle\-sfv\-console\fP  Utility to verify files.
Winsfv files, md5sum and sha1sum files are supported
.SH COMMANDS
.TP
.B \-\-version
output version information and exit
.TP
.B \-\-help
display a option overview and exit

.SH OPTIONS
TODO
.SH AUTHOR
This manual page was written by Alberto Fernandez <infjaf@gmail.com>.
