.TH OPENHACHA-GTK "1" "March 30, 2009"
.SH NAME
openhacha-gtk \- Utility to join fragments of files that were splited with other software.

.SH SYNOPSIS
.B openhacha-gtk

.SH DESCRIPTION
\fBopenhacha-gtk\fP  Utility to join fragments of files that were splited with other software.
Dalle support a wide variety of formats so you can work with a unique application to work with these files.

.SH AUTHOR
This manual page was written by Alberto Fernandez <infjaf@gmail.com>.
