using System.Reflection;
using System.Runtime.CompilerServices;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("OpenHacha")]
[assembly: AssemblyDescriptionAttribute("A free as in freedom implementation of Hacha")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2003-2004, Ramón Rey Vicente")]
[assembly: AssemblyVersionAttribute("0.7.8.2")]

