Document: dalle
Title: Debian dalle Manual
Author: <insert document author here>
Abstract: This manual describes what dalle is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dalle/dalle.sgml.gz

Format: postscript
Files: /usr/share/doc/dalle/dalle.ps.gz

Format: text
Files: /usr/share/doc/dalle/dalle.text.gz

Format: HTML
Index: /usr/share/doc/dalle/html/index.html
Files: /usr/share/doc/dalle/html/*.html

  
