using System.Reflection;
using System.Runtime.CompilerServices;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Dalle-swf")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("Dalle")]
[assembly: AssemblyProductAttribute("dalle-swf")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2005-2010, Alberto Fernández")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("0.10.4.1")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyKeyFileAttribute("dalle.key")]
[assembly: AssemblyKeyNameAttribute("")]

