using System.Reflection;
using System.Runtime.CompilerServices;

// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("Dalle-console")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyConfigurationAttribute("")]
[assembly: AssemblyCompanyAttribute("Dalle")]
[assembly: AssemblyProductAttribute("dalle-console")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2003-2011, Alberto Fernández")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.12.04.1")]
[assembly: AssemblyDelaySignAttribute(false)]

